### ISSUE TITLE
Placement new with Jolt allocators

### ISSUE THREAD

**Issue by jdumas** [jrouwe/JoltPhysics#1009]
Hi,

I'm having some trouble using Jolt's [overidden new/delete operators](https://github.com/jrouwe/JoltPhysics/blob/f5ab4fd526fe1e03a408a5ead3ee396263d8a1d3/Jolt/Core/Memory.h#L29-L37) with a placement new syntax. Here is an example code:

```c++
using T = JPH::BodyID;
T source;
T target;
new(&target) T(source);
```

Which compiles with the following error (Xcode15.3 on macOS, using Jolt 4.0.2):

```
/Users/jedumas/external/git/JoltPhysicsHelloWorld/Source/HelloWorld.cpp:366:2: error: no matching function for call to 'operator new'
        new(&target) T(source);
        ^  ~~~~~~~~~
/Users/jedumas/external/git/JoltPhysicsHelloWorld/Build/build/_deps/joltphysics-src/Build/../Jolt/Physics/Body/BodyID.h:15:2: note: candidate function not viable: no known conversion from 'T *' (aka 'JPH::BodyID *') to 'std::align_val_t' for 2nd argument
        JPH_OVERRIDE_NEW_DELETE
        ^
/Users/jedumas/external/git/JoltPhysicsHelloWorld/Build/build/_deps/joltphysics-src/Build/../Jolt/Core/Memory.h:34:19: note: expanded from macro 'JPH_OVERRIDE_NEW_DELETE'
        JPH_INLINE void *operator new (size_t inCount, std::align_val_t inAlignment)                            { return JPH::AlignedAllocate(inCount, static_cast<size_t>(inAlignment)); } \
                         ^
/Users/jedumas/external/git/JoltPhysicsHelloWorld/Build/build/_deps/joltphysics-src/Build/../Jolt/Physics/Body/BodyID.h:15:2: note: candidate function not viable: requires single argument 'inCount', but 2 arguments were provided
/Users/jedumas/external/git/JoltPhysicsHelloWorld/Build/build/_deps/joltphysics-src/Build/../Jolt/Core/Memory.h:30:19: note: expanded from macro 'JPH_OVERRIDE_NEW_DELETE'
        JPH_INLINE void *operator new (size_t inCount)                                                                                          { return JPH::Allocate(inCount); } \
                         ^
1 error generated.
```

When compiling with `JPH_DISABLE_CUSTOM_ALLOCATOR` defined the error goes away.

**Comment by jrouwe** [comment]
See: https://github.com/jrouwe/JoltPhysics/discussions/986

**Comment by jdumas** [comment]
Thanks!
